# Dockerfile.dev
FROM node:20-alpine

# Set working dir
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install


# Copy source files
COPY . .

# Expose your backend port
EXPOSE 3000

# Set dev mode
ENV NODE_ENV=development

# Start with hot reload
CMD ["npm", "run", "dev"]
